local M = {}

M.lsp_cmd = {
  "fortls",
  "--nthreads",
  "10",
  "--lowercase_intrinsics",
  "--hover_signature",
  "--hover_language=fortran",
  "--use_signature_help",
  "--disable_diagnostic",
  "--incremental_sync",
  "--recursion_limit",
  "1000",
  "--source_dirs",
  os.getenv("DROPBOX") .. "/easifem/base/src/**",
  os.getenv("DROPBOX") .. "/easifem/classes/src/**",
  -- os.getenv("DROPBOX") .. "/easifem/oneDimElasticity/src/**",
  os.getenv("DROPBOX") .. "/easifem/oneDimSTFEM/src/**",
  -- os.getenv("DROPBOX") .. "/easifem/oneDimLayeredMedia/src/**",
  os.getenv("DROPBOX") .. "/easifem/diffusionKernel/src/**",
  os.getenv("DROPBOX") .. "/easifem/elasticityKernel/src/**",
  os.getenv("DROPBOX") .. "/easifem/dispersionAnalysis/src/**",
  os.getenv("HOME") .. "/.easifem/src/tomlf/src/**",
}

M.linter = {
  "-c",
  "-fsyntax-only",
  "-cpp",
  -- "-fdiagnostics-plain-output",
  "-Wunused-variable",
  "-Wunused-dummy-argument",
  "-Wno-c-binding-type",
  "-Wall",
  "-I",
  os.getenv("HOME") .. "/.easifem/lint/include/",
  "-I",
  os.getenv("HOME") .. "/.easifem/install/base/include/",
  "-I",
  os.getenv("HOME") .. "/.easifem/install/classes/include/",
  "-I",
  os.getenv("HOME") .. "/.easifem/install/oneDimSTFEM/include/",
  -- "-I",
  -- os.getenv("HOME") .. "/.easifem/install/oneDimElasticity/include/",
  -- "-I",
  -- os.getenv("HOME") .. "/.easifem/install/oneDimLayeredMedia/include/",
  "-I",
  os.getenv("HOME") .. "/.easifem/install/elasticity/include/",
  "-I",
  os.getenv("HOME") .. "/.easifem/install/dispersionAnalysis/include/",
  "-I",
  os.getenv("HOME") .. "/.easifem/install/tomlf/include/toml-f/modules/",
  "-J",
  os.getenv("HOME") .. "/.easifem/lint/include/",
  "-DDEBUG_VER",
}

M.formatter = {
  "--line-length",
  "78",
  "--indent",
  "2",
  "--strict-indent",
  "--disable-indent-mod",
  "--whitespace",
  "2",
  "--whitespace-comma",
  "--whitespace-assignment",
  "--enable-decl",
  "--whitespace-decl",
  "--whitespace-relational",
  "--whitespace-logical",
  "--whitespace-multdiv",
  "--whitespace-print",
  "--whitespace-intrinsics",
  "--strip-comments",
  "--case",
  "2",
  "2",
  "2",
  "2",
}

return M
